# .gitlab-ci.yml
stages:
  - deploy

pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public
  artifacts:
    paths:
      - .public
  only:
    - main  # Adjust branch name if different

