[build]
  command = """
    curl -sL https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz | tar xz
    mkdir -p /opt/build/bin
    mv zola /opt/build/bin/zola
    export PATH=/opt/build/bin:$PATH
    zola build
  """
  publish = "public"