[build]
  command = """
  curl -sL https://github.com/getzola/zola/releases/download/v0.17.2/zola-v0.17.2-x86_64-unknown-linux-gnu.tar.gz --output zola.tar.gz
  if [ $? -ne 0 ]; then
      echo "Failed to download Zola."
      exit 1
  fi

  tar -xzf zola.tar.gz
  if [ $? -ne 0 ]; then
      echo "Failed to extract Zola."
      exit 1
  fi

  mkdir -p /opt/build/bin
  mv zola /opt/build/bin/zola
  export PATH=/opt/build/bin:$PATH
  zola build
  """
  publish = "public"