[build]
  command = """
  curl -sL https://github.com/getzola/zola/releases/latest/download/zola-v0.19.2-x86_64-unknown-linux-gnu.tar.gz --output zola.tar.gz
  tar -xzf zola.tar.gz
  mkdir -p /opt/build/bin
  mv zola /opt/build/bin/zola
  export PATH=/opt/build/bin:$PATH
  zola build
  """
  publish = "public"

[build.environment]
  GIT_SUBMODULE_STRATEGY = "recursive"
